### PR TITLE
freeze hummingbot version

### PR DESCRIPTION
**Pull request by david-hummingbot**
- freezing hb version for now to because of conf error

### CODE REVIEW

**Review by cardosofede — APPROVED** [review]

**Comment by komposter** [comment]
Hi there!
I'm trying to install and run the latest backend-api with Conda and it fails (I already successfully ran previous versions, so the problem is with this update).

Firstly, I tried to update an existing environment:
```
conda deactivate
make uninstall
make install
```

Then I tried to make a clear installation. And I always get this error:
```
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: - Ran pip subprocess with arguments:
['/Users/komposter/miniconda3/envs/backend-api/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/komposter/dev/hummingbot-backend-api/condaenv.6eo9u__e.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting git+https://github.com/felixfontein/docker-py (from -r /Users/komposter/dev/hummingbot-backend-api/condaenv.6eo9u__e.requirements.txt (line 3))
  Cloning https://github.com/felixfontein/docker-py to /private/var/folders/1g/dynft1h14x3gnr8x8v63l6900000gn/T/pip-req-build-4efb2vdl
  Resolved https://github.com/felixfontein/docker-py to commit 03e43be6af9b21f9f966eb84ca46a159b664ccf4
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting git+https://github.com/hummingbot/hbot-remote-client-py.git (from -r /Users/komposter/dev/hummingbot-backend-api/condaenv.6eo9u__e.requirements.txt (line 8))
  Cloning https://github.com/hummingbot/hbot-remote-client-py.git to /private/var/folders/1g/dynft1h14x3gnr8x8v63l6900000gn/T/pip-req-build-ut8d5vs0
  Resolved https://github.com/hummingbot/hbot-remote-client-py.git to commit 5fa09e966f41593cdbc6c183a2d19f43ab4880c2
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting hummingbot==20241125 (from -r /Users/komposter/dev/hummingbot-backend-api/condaenv.6eo9u__e.requirements.txt (line 1))
  Using cached hummingbot-20241125.tar.gz (6.7 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/felixfontein/docker-py /private/var/folders/1g/dynft1h14x3gnr8x8v63l6900000gn/T/pip-req-build-4efb2vdl
  Running command git clone --filter=blob:none --quiet https://github.com/hummingbot/hbot-remote-client-py.git /private/var/folders/1g/dynft1h14x3gnr8x8v63l6900000gn/T/pip-req-build-ut8d5vs0
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
      Traceback (most recent call last):
        File "/Users/komposter/miniconda3/envs/backend-api/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/komposter/miniconda3/envs/backend-api/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/komposter/miniconda3/envs/backend-api/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/1g/dynft1h14x3gnr8x8v63l6900000gn/T/pip-build-env-xigji6tx/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/private/var/folders/1g/dynft1h14x3gnr8x8v63l6900000gn/T/pip-build-env-xigji6tx/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/1g/dynft1h14x3gnr8x8v63l6900000gn/T/pip-build-env-xigji6tx/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/1g/dynft1h14x3gnr8x8v63l6900000gn/T/pip-build-env-xigji6tx/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 169, in <module>
        File "<string>", line 157, in main
        File "/private/var/folders/1g/dynft1h14x3gnr8x8v63l6900000gn/T/pip-build-env-xigji6tx/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 979, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/private/var/folders/1g/dynft1h14x3gnr8x8v63l6900000gn/T/pip-build-env-xigji6tx/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 821, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/private/var/folders/1g/dynft1h14x3gnr8x8v63l6900000gn/T/pip-build-env-xigji6tx/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 116, in nonempty
          raise ValueError(error_msg)
      ValueError: 'hummingbot/**/*.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
                                                                                                                                                                                                                                                                                                                   failed

CondaEnvException: Pip failed

make: *** [install] Error 1
```

If I replace `hummingbot==20241125` with `hummingbot` in environment.yml, installation finishes successfully, but I can't run the backend-api because of the [Dexalot error](https://github.com/hummingbot/backend-api/issues/43).

Any suggestions on how to fix this?
Thank you!

**Comment by komposter** [comment]
> @komposter try using the `hummingbot==20241124` version instead

Thank you! Successfully installed and ran it!

**Comment by komposter** [comment]
> @komposter try using the `hummingbot==20241124` version instead

@david-hummingbot 
It worked for me for a while. But now when I try to reinstall it, it doesn't work again.

With `hummingbot==20241124`, as well as with `hummingbot` without version, I'm getting this in runtime:
```
ImportError: cannot import name 'int_to_big_endian' from 'eth_keyfile.keyfile' (/Users/komposter/miniconda3/envs/backend-api/lib/python3.10/site-packages/eth_keyfile/keyfile.py)
```

And with `hummingbot==20241125` I have the same issue as I had before on the installation stage -- https://github.com/hummingbot/backend-api/pull/50#issuecomment-2569082661

What's the solution? How to install it now?
Thanks for your support!

**Comment by komposter** [comment]
It's working now with `hummingbot==20250220`

**Pull request merged**
